"""
hsp_family.py - the Hidden Subgroup Problem family for the decodability gradient.

A permutation-group toolkit + a ladder of groups sliding from abelian (cyclic,
Shor/Fourier-decodable) through dihedral (the known hard wall, lattice-linked) to
symmetric (deeply non-abelian). For each group we build the HSP coset grating and
measure how much of it the holographic/scalar readout can recover.

THE ORDER PARAMETER (rigorous):
  A function constant on cosets of H has its abelian (1-D character) Fourier energy
  supported exactly on H-perp.  The energy recoverable by 1-D characters trivial on
  H equals the energy surviving pushforward to G / ([G,G]*H).  For ABELIAN G this is
  the WHOLE signal (Phi = 1, fully decodable - Shor).  For non-abelian G the coset
  structure leaks into the >=2-dimensional irreps that 1-D / scalar / phase-cavity
  readouts cannot resolve, so Phi collapses toward the random-null floor.  The
  collapse is governed by |[G,G]| (equivalently d_max, the max irrep dimension).

Square operators here are |G|-dim (dim_G) regular-representation objects, never a
variable-indexed local constraint matrix.
"""
import numpy as np


# ----------------------------- permutation algebra -----------------------------
def compose(a, b):
    return tuple(a[b[i]] for i in range(len(a)))


def inverse(a):
    inv = [0] * len(a)
    for i, x in enumerate(a):
        inv[x] = i
    return tuple(inv)


def identity(n):
    return tuple(range(n))


def generate(gens):
    """BFS closure, returned as an ORDERED list (BFS order). For a cyclic group
    generated by an n-cycle this yields the natural generator-power ordering, so
    the scalar FFT readout sees the true periodicity."""
    n = len(gens[0])
    seen = {identity(n)}
    order = [identity(n)]
    frontier = [identity(n)]
    while frontier:
        x = frontier.pop(0)
        for g in gens:
            for y in (compose(g, x), compose(x, g)):
                if y not in seen:
                    seen.add(y)
                    order.append(y)
                    frontier.append(y)
    return order


def subgroup(elems, n):
    G = {identity(n)}
    for e in elems:
        G.add(e)
    frontier = list(G)
    while frontier:
        x = frontier.pop()
        for g in list(G):
            y = compose(g, x)
            if y not in G:
                G.add(y)
                frontier.append(y)
    return G


def commutator_subgroup(Gset, n):
    Gl = list(Gset)
    comms = []
    for a in Gl:
        ia = inverse(a)
        for b in Gl:
            ib = inverse(b)
            comms.append(compose(compose(a, b), compose(ia, ib)))  # (a b)(a^-1 b^-1) = a b a^-1 b^-1
    return subgroup(comms, n)


def left_cosets(Gset, Hset, n):
    """Partition G into left cosets gH."""
    remaining = set(Gset)
    cosets = []
    Hl = list(Hset)
    while remaining:
        g = next(iter(remaining))
        c = set(compose(g, h) for h in Hl)
        cosets.append(frozenset(c))
        remaining -= c
    return cosets


# ----------------------------- group constructors ------------------------------
def cyclic(n):
    return [tuple((i + 1) % n for i in range(n))], n


def dihedral(m):
    r = tuple((i + 1) % m for i in range(m))
    s = tuple((-i) % m for i in range(m))
    return [r, s], m


def symmetric(n):
    a = tuple([1, 0] + list(range(2, n)))
    c = tuple((i + 1) % n for i in range(n))
    return [a, c], n


def alternating(n):
    g1 = list(range(n)); g1[0], g1[1], g1[2] = 1, 2, 0
    g2 = list(range(n)); g2[1], g2[2], g2[3] = 2, 3, 1
    return [tuple(g1), tuple(g2)], n


def involution_subgroup(Gset, n):
    """A uniform HARD hidden subgroup of order 2 across the ladder: <t> for some
    fixed-structure involution t (a transposition / reflection / half-rotation).
    For non-abelian G this is transverse to [G,G] - the hard HSP case."""
    # prefer a transposition-like involution swapping two points
    cand = tuple([1, 0] + list(range(2, n)))
    if cand in Gset:
        return subgroup([cand], n)
    # else any non-identity involution
    for g in Gset:
        if g != identity(n) and compose(g, g) == identity(n):
            return subgroup([g], n)
    return subgroup([identity(n)], n)


# The ladder. d_max (max irrep dim) is a KNOWN structural fact used only as the
# x-axis label; the measured order parameter Phi is computed, never assigned.
def build_ladder():
    ladder = []
    for n in (16, 24, 32, 48, 64):
        gens, pts = cyclic(n)
        ladder.append(("Z_%d" % n, gens, pts, 1))
    for m in (8, 12, 16, 24, 32):
        gens, pts = dihedral(m)
        ladder.append(("D_%d" % m, gens, pts, 2))
    for nm, fn, n, dm in (("A_4", alternating, 4, 3), ("S_4", symmetric, 4, 3), ("S_5", symmetric, 5, 4)):
        gens, pts = fn(n)
        ladder.append((nm, gens, pts, dm))
    return ladder


# ----------------------------- the decodability measure ------------------------
class GroupInstance:
    def __init__(self, name, gens, pts, d_max):
        self.name = name
        self.n = pts
        self.d_max = d_max
        self.elems = generate(gens)              # ordered list (BFS)
        self.G = set(self.elems)
        self.order = len(self.G)
        self.comm = commutator_subgroup(self.G, pts)        # [G,G]
        self.G_ab_order = self.order // len(self.comm)       # |G^ab|
        self.abelianness = self.G_ab_order / self.order      # K1-related (1 for abelian)
        self.H = involution_subgroup(self.G, pts)            # hidden subgroup (order 2, hard)
        self.K = subgroup(list(self.comm) + list(self.H), pts)  # [G,G]*H
        self.H_cosets = left_cosets(self.G, self.H, pts)
        self.K_cosets = left_cosets(self.G, self.K, pts)
        self.idx = {g: i for i, g in enumerate(self.elems)}

    def coset_grating(self, rng):
        """v[g] = random unit phase of the H-coset of g (the HSP encoding)."""
        phase = {c: np.exp(1j * rng.uniform(0, 2 * np.pi)) for c in self.H_cosets}
        member = {}
        for c in self.H_cosets:
            for g in c:
                member[g] = phase[c]
        return np.array([member[g] for g in self.elems], dtype=np.complex128)

    def random_grating(self, rng):
        ph = rng.uniform(0, 2 * np.pi, size=self.order)
        return np.exp(1j * ph)

    def phi_character(self, v):
        """Energy of v recoverable by 1-D characters trivial on H = energy
        surviving pushforward to G/K, K=[G,G]*H.  Phi=1 for abelian, collapses
        as |[G,G]| grows."""
        num = 0.0
        for c in self.K_cosets:
            m = np.mean([v[self.idx[g]] for g in c])
            num += (abs(m) ** 2) * len(c)
        return float(num / (np.sum(np.abs(v) ** 2)))

    def phi_fft(self, v):
        """The literal scalar holographic readout: FFT concentration in the top
        [G:H] bins (the number of cosets), normalized to [0,1]."""
        V = np.abs(np.fft.fft(v)) ** 2
        k = len(self.H_cosets)
        top = np.sort(V)[::-1][:k].sum()
        return float(top / (V.sum() + 1e-30))
