#ifndef CATCAS_ORBIT_QUERY_RUNTIME_H
#define CATCAS_ORBIT_QUERY_RUNTIME_H

#include <stdint.h>

#define ORBIT_QUERY_SCHEMA_RAW "CAT_CAS_ORBIT_QUERY_RAW_RECORD_V1"
#define ORBIT_QUERY_SCHEMA_MANIFEST "CAT_CAS_ORBIT_QUERY_CAPTURE_MANIFEST_V1"
#define ORBIT_QUERY_SCHEMA_UNBLIND "CAT_CAS_ORBIT_QUERY_UNBLINDING_MAP_V1"
#define ORBIT_QUERY_SCHEMA_SUMMARY "CAT_CAS_ORBIT_QUERY_RUNTIME_SUMMARY_V1"

#define ORBIT_QUERY_MODULUS 256U
#define ORBIT_QUERY_MEMBER_D 23U
#define ORBIT_QUERY_MEMBER_FOLD 233U
#define ORBIT_QUERY_EQUAL_MEMBER 0U
#define ORBIT_QUERY_PHASE_COUNT 4U
#define ORBIT_QUERY_CONDITION_COUNT 10U
#define ORBIT_QUERY_BASE_WORK 2048U
#define ORBIT_QUERY_QUANT_SCALE 1024.0
#define ORBIT_QUERY_TOTAL_WORK (2U * ORBIT_QUERY_BASE_WORK)
#define ORBIT_QUERY_BANK_LINES 4096U
#define ORBIT_QUERY_LINE_BYTES 64U
#define ORBIT_QUERY_HOME_CORE 4
#define ORBIT_QUERY_RECEIVER_CORE 5
#define ORBIT_QUERY_OPERATOR_ITERATIONS 1U

typedef struct {
    uint32_t modulus;
    uint32_t member;
} OrbitState;

#endif
