#ifndef CATCAS_INDEPENDENT_WINDOW_RUNTIME_H
#define CATCAS_INDEPENDENT_WINDOW_RUNTIME_H

#include <stdint.h>

#define INDEPENDENT_WINDOW_RUN_ID "independent_window_transducer_v3_0"
#define INDEPENDENT_WINDOW_SCHEMA_RAW "CAT_CAS_INDEPENDENT_WINDOW_RAW_COMPONENT_RECORD_V3"
#define INDEPENDENT_WINDOW_SCHEMA_SENTINEL "CAT_CAS_INDEPENDENT_WINDOW_RESTORATION_SENTINEL_V3"
#define INDEPENDENT_WINDOW_SCHEMA_RUNTIME_SUMMARY "CAT_CAS_INDEPENDENT_WINDOW_RUNTIME_SUMMARY_V3"

#define INDEPENDENT_WINDOW_REPLICATES 2
#define INDEPENDENT_WINDOW_Q_COUNT 7
#define INDEPENDENT_WINDOW_MAPPING_COUNT 2
#define INDEPENDENT_WINDOW_SOURCE_ORDER_COUNT 2
#define INDEPENDENT_WINDOW_SUBCAPTURE_ORDER_COUNT 2
#define INDEPENDENT_WINDOW_Q0_REPEAT_COUNT 2
#define INDEPENDENT_WINDOW_NONZERO_PAIR_COUNT_PER_REPLICATE 24
#define INDEPENDENT_WINDOW_Q0_PAIR_COUNT_PER_REPLICATE 8
#define INDEPENDENT_WINDOW_PAIR_COUNT_PER_REPLICATE 32
#define INDEPENDENT_WINDOW_TRIALS_PER_REPLICATE 64
#define INDEPENDENT_WINDOW_TOTAL_TRIALS 128
#define INDEPENDENT_WINDOW_TOTAL_COMPONENT_WINDOWS 256

#define INDEPENDENT_WINDOW_BASE_WORK 2048
#define INDEPENDENT_WINDOW_TOTAL_WORK 4096
#define INDEPENDENT_WINDOW_SOURCE_WORK_PER_SUBCAPTURE 4096
#define INDEPENDENT_WINDOW_SOURCE_WORK_PER_MAPPING_LEG 8192
#define INDEPENDENT_WINDOW_BANK_LINES 4096u
#define INDEPENDENT_WINDOW_LINE_BYTES 64u
#define INDEPENDENT_WINDOW_BANK_BYTES \
    (INDEPENDENT_WINDOW_BANK_LINES * INDEPENDENT_WINDOW_LINE_BYTES)
#define INDEPENDENT_WINDOW_SOURCE_CORE 4
#define INDEPENDENT_WINDOW_RECEIVER_CORE 5
#define INDEPENDENT_WINDOW_PERM_A 257u
#define INDEPENDENT_WINDOW_PERM_B 43u

#define INDEPENDENT_WINDOW_EVENT_CYCLES_CONFIG 0x0076ull
#define INDEPENDENT_WINDOW_EVENT_C2D_CONFIG 0x20eaull
#define INDEPENDENT_WINDOW_EVENT_PROBE_DIRTY_CONFIG 0x0cecull

typedef enum {
    INDEPENDENT_WINDOW_Q0_SIGNAL = 0,
    INDEPENDENT_WINDOW_Q0_NULL_BUILD = 1,
    INDEPENDENT_WINDOW_Q0_NULL_TEST = 2
} IndependentWindowQ0Role;

typedef struct {
    int replicate;
    int pair_index;
    int leg_index;
    int trial_index;
    int repeat_index;
    int q;
    int mapping;
    int mapping_order_first;
    int source_positive_first;
    int positive_subcapture_first;
    int q0_role;
} IndependentWindowTrial;

uint32_t independent_window_positive_work(int q);
uint32_t independent_window_negative_work(int q);
uint32_t independent_window_permuted_line(uint32_t index);
int independent_window_validate_schedule_tsv(const char *path);

#endif
