#!/usr/bin/env python3
"""
MCP Access Validator - Validation Script

Validates that the skill produces correct outputs for given inputs.
"""

import json
import sys
from pathlib import Path

def validate(input_path: str, expected_path: str) -> int:
    """
    Validate that the skill produces the expected output.
    Returns 0 for success, 1 for failure.
    """
    try:
        # Read actual output (generated by run.py)
        with open(input_path, 'r', encoding='utf-8') as f:
            actual = json.load(f)
        
        # Read expected output
        with open(expected_path, 'r', encoding='utf-8') as f:
            expected = json.load(f)
        
        # Basic validation: check required fields
        required_fields = ["validation_passed", "token_waste_detected"]
        for field in required_fields:
            if field not in actual:
                print(f"ERROR: Missing required field '{field}' in actual output")
                return 1
        
        # Compare validation_passed (must match exactly)
        if actual.get("validation_passed") != expected.get("validation_passed"):
            print(f"ERROR: validation_passed mismatch. Actual: {actual.get('validation_passed')}, Expected: {expected.get('validation_passed')}")
            return 1
        
        # Compare token_waste_detected (must match exactly)
        if actual.get("token_waste_detected") != expected.get("token_waste_detected"):
            print(f"ERROR: token_waste_detected mismatch. Actual: {actual.get('token_waste_detected')}, Expected: {expected.get('token_waste_detected')}")
            return 1
        
        # Check that recommended tool is present when waste detected
        if actual.get("token_waste_detected") and not actual.get("recommended_mcp_tool"):
            print("ERROR: token_waste_detected is True but no recommended_mcp_tool provided")
            return 1
        
        # Check audit entry structure
        audit_entry = actual.get("audit_entry")
        if not audit_entry:
            print("ERROR: Missing audit_entry in output")
            return 1
        
        required_audit_fields = ["audit_id", "timestamp", "skill", "validation_passed"]
        for field in required_audit_fields:
            if field not in audit_entry:
                print(f"ERROR: Missing audit field '{field}'")
                return 1
        
        # Check that skill name is correct
        if audit_entry.get("skill") != "mcp-access-validator":
            print(f"ERROR: Wrong skill name in audit: {audit_entry.get('skill')}")
            return 1
        
        # All checks passed
        print("VALIDATION PASSED")
        print(f"  validation_passed: {actual.get('validation_passed')}")
        print(f"  token_waste_detected: {actual.get('token_waste_detected')}")
        if actual.get("recommended_mcp_tool"):
            print(f"  recommended_tool: {actual.get('recommended_mcp_tool')}")
        print(f"  estimated_savings: {actual.get('estimated_token_savings', 'N/A')}")
        
        return 0
        
    except FileNotFoundError as e:
        print(f"ERROR: File not found: {e}")
        return 1
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON: {e}")
        return 1
    except Exception as e:
        print(f"ERROR: Validation failed: {e}")
        return 1

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python validate.py <actual_output.json> <expected_output.json>")
        sys.exit(1)
    
    exit_code = validate(sys.argv[1], sys.argv[2])
    sys.exit(exit_code)