#ifndef CATCAS_CONFIRMATION_V2_RUNTIME_H
#define CATCAS_CONFIRMATION_V2_RUNTIME_H

#include <stdint.h>

#define BALANCED_TRANSDUCER_SCHEMA_RAW "CAT_CAS_BALANCED_TRANSDUCER_CONFIRMATION_RAW_RECORD_V2"
#define BALANCED_TRANSDUCER_SCHEMA_SENTINEL "CAT_CAS_BALANCED_TRANSDUCER_CONFIRMATION_RESTORATION_SENTINEL_V2"
#define BALANCED_TRANSDUCER_SCHEMA_SUMMARY "CAT_CAS_BALANCED_TRANSDUCER_CONFIRMATION_RUNTIME_SUMMARY_V2"

#define BALANCED_TRANSDUCER_REPLICATES 2
#define BALANCED_TRANSDUCER_Q_COUNT 7
#define BALANCED_TRANSDUCER_MAPPING_COUNT 2
#define BALANCED_TRANSDUCER_TRIALS_PER_Q_MAPPING 4
#define BALANCED_TRANSDUCER_PAIR_COUNT_PER_REPLICATE \
    (BALANCED_TRANSDUCER_Q_COUNT * BALANCED_TRANSDUCER_TRIALS_PER_Q_MAPPING)
#define BALANCED_TRANSDUCER_TRIALS_PER_REPLICATE \
    (BALANCED_TRANSDUCER_Q_COUNT * BALANCED_TRANSDUCER_MAPPING_COUNT * BALANCED_TRANSDUCER_TRIALS_PER_Q_MAPPING)

#define BALANCED_TRANSDUCER_BASE_WORK 2048
#define BALANCED_TRANSDUCER_TOTAL_WORK 4096
#define BALANCED_TRANSDUCER_BANK_LINES 4096u
#define BALANCED_TRANSDUCER_LINE_BYTES 64u
#define BALANCED_TRANSDUCER_BANK_BYTES \
    (BALANCED_TRANSDUCER_BANK_LINES * BALANCED_TRANSDUCER_LINE_BYTES)
#define BALANCED_TRANSDUCER_SENTINEL_SEGMENTS 4u
#define BALANCED_TRANSDUCER_SENTINEL_LINES_PER_SEGMENT 512u
#define BALANCED_TRANSDUCER_SENTINEL_LINES \
    (BALANCED_TRANSDUCER_SENTINEL_SEGMENTS * BALANCED_TRANSDUCER_SENTINEL_LINES_PER_SEGMENT)
#define BALANCED_TRANSDUCER_SOURCE_CORE 4
#define BALANCED_TRANSDUCER_RECEIVER_CORE 5
#define BALANCED_TRANSDUCER_PERM_A 257u
#define BALANCED_TRANSDUCER_PERM_B 43u

#define BALANCED_TRANSDUCER_EVENT_CYCLES_CONFIG 0x0076ull
#define BALANCED_TRANSDUCER_EVENT_C2D_CONFIG 0x20eaull
#define BALANCED_TRANSDUCER_EVENT_PROBE_DIRTY_CONFIG 0x0cecull

typedef struct {
    int replicate;
    int pair_index;
    int leg_index;
    int trial_index;
    int repeat_index;
    int q;
    int mapping;
    int mapping_order_first;
    int source_positive_first;
    int receiver_positive_first;
} BalancedTrial;

#endif
