#ifndef FAMILY10H_RELATION_SPATIAL_RUNTIME_H
#define FAMILY10H_RELATION_SPATIAL_RUNTIME_H

#include <stdint.h>

#define FAMILY10H_RELATION_SPATIAL_TOTAL_WORK 4096u
#define FAMILY10H_RELATION_SPATIAL_LINE_COUNT 4096u
#define FAMILY10H_RELATION_SPATIAL_LINE_BYTES 64u
#define FAMILY10H_RELATION_SPATIAL_LANE_BYTES 262144u
#define FAMILY10H_RELATION_SPATIAL_PAIR_SAMPLE_COUNT 256u
#define FAMILY10H_RELATION_SPATIAL_PAIR_SAMPLE_STRIDE 16u

typedef enum relation_spatial_relation_id {
    RELATION_SPATIAL_R0 = 0,
    RELATION_SPATIAL_R1 = 1
} relation_spatial_relation_id;

typedef enum relation_spatial_order_id {
    RELATION_SPATIAL_ORDER_AB = 0,
    RELATION_SPATIAL_ORDER_BA = 1
} relation_spatial_order_id;

typedef enum relation_spatial_control_id {
    RELATION_SPATIAL_CONTROL_NONE = 0,
    RELATION_SPATIAL_CONTROL_RELATION_SHAM = 1,
    RELATION_SPATIAL_CONTROL_SCRAMBLED_PAIR = 2,
    RELATION_SPATIAL_CONTROL_ROUTE_PRESSURE = 3,
    RELATION_SPATIAL_CONTROL_DISTANCE_MATCHED = 4,
    RELATION_SPATIAL_CONTROL_DEAD_PRIMARY = 5,
    RELATION_SPATIAL_CONTROL_DEAD_SHAM = 6,
    RELATION_SPATIAL_CONTROL_RESET_FLUSH_PRIMARY = 7,
    RELATION_SPATIAL_CONTROL_RESET_FLUSH_SHAM = 8,
    RELATION_SPATIAL_CONTROL_RESET_PREFAULT_FLUSH_PRIMARY = 9,
    RELATION_SPATIAL_CONTROL_RESET_PREFAULT_FLUSH_SHAM = 10,
    RELATION_SPATIAL_CONTROL_RESET_DOUBLE_FLUSH_PRIMARY = 11,
    RELATION_SPATIAL_CONTROL_RESET_DOUBLE_FLUSH_SHAM = 12,
    RELATION_SPATIAL_CONTROL_RESET_LANE_A_FLUSH_PRIMARY = 13,
    RELATION_SPATIAL_CONTROL_RESET_LANE_A_FLUSH_SHAM = 14,
    RELATION_SPATIAL_CONTROL_RESTORE_SAME_PRIMARY = 15,
    RELATION_SPATIAL_CONTROL_RESTORE_SAME_SHAM = 16,
    RELATION_SPATIAL_CONTROL_RESTORE_OPPOSITE_PRIMARY = 17,
    RELATION_SPATIAL_CONTROL_RESTORE_OPPOSITE_SHAM = 18,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_PRIMARY = 19,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_SHAM = 20,
    RELATION_SPATIAL_CONTROL_COMPOSE_R0_R1_PRIMARY = 21,
    RELATION_SPATIAL_CONTROL_COMPOSE_R0_R1_SHAM = 22,
    RELATION_SPATIAL_CONTROL_COMPOSE_R1_R0_PRIMARY = 23,
    RELATION_SPATIAL_CONTROL_COMPOSE_R1_R0_SHAM = 24,
    RELATION_SPATIAL_CONTROL_DEAD_COMPOSE_R0_R1_PRIMARY = 25,
    RELATION_SPATIAL_CONTROL_DEAD_COMPOSE_R0_R1_SHAM = 26,
    RELATION_SPATIAL_CONTROL_DEAD_COMPOSE_R1_R0_PRIMARY = 27,
    RELATION_SPATIAL_CONTROL_DEAD_COMPOSE_R1_R0_SHAM = 28,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_COMPOSE_R0_R1_PRIMARY = 29,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_COMPOSE_R0_R1_SHAM = 30,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_COMPOSE_R1_R0_PRIMARY = 31,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_COMPOSE_R1_R0_SHAM = 32,
    RELATION_SPATIAL_CONTROL_NEUTRAL_COMPOSE_PRIMARY = 33,
    RELATION_SPATIAL_CONTROL_NEUTRAL_COMPOSE_SHAM = 34,
    RELATION_SPATIAL_CONTROL_RANDOM_COMPOSE_PRIMARY = 35,
    RELATION_SPATIAL_CONTROL_RANDOM_COMPOSE_SHAM = 36,
    RELATION_SPATIAL_CONTROL_GAPPED_COMPOSE_R0_R1_PRIMARY = 37,
    RELATION_SPATIAL_CONTROL_GAPPED_COMPOSE_R0_R1_SHAM = 38,
    RELATION_SPATIAL_CONTROL_GAPPED_COMPOSE_R1_R0_PRIMARY = 39,
    RELATION_SPATIAL_CONTROL_GAPPED_COMPOSE_R1_R0_SHAM = 40,
    RELATION_SPATIAL_CONTROL_BALANCED_ALT_A_PRIMARY = 41,
    RELATION_SPATIAL_CONTROL_BALANCED_ALT_A_SHAM = 42,
    RELATION_SPATIAL_CONTROL_BALANCED_ALT_B_PRIMARY = 43,
    RELATION_SPATIAL_CONTROL_BALANCED_ALT_B_SHAM = 44,
    RELATION_SPATIAL_CONTROL_DEAD_BALANCED_ALT_A_PRIMARY = 45,
    RELATION_SPATIAL_CONTROL_DEAD_BALANCED_ALT_A_SHAM = 46,
    RELATION_SPATIAL_CONTROL_DEAD_BALANCED_ALT_B_PRIMARY = 47,
    RELATION_SPATIAL_CONTROL_DEAD_BALANCED_ALT_B_SHAM = 48,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_BALANCED_ALT_A_PRIMARY = 49,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_BALANCED_ALT_A_SHAM = 50,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_BALANCED_ALT_B_PRIMARY = 51,
    RELATION_SPATIAL_CONTROL_SOURCE_OFF_BALANCED_ALT_B_SHAM = 52,
    RELATION_SPATIAL_CONTROL_GAPPED_BALANCED_ALT_A_PRIMARY = 53,
    RELATION_SPATIAL_CONTROL_GAPPED_BALANCED_ALT_A_SHAM = 54,
    RELATION_SPATIAL_CONTROL_GAPPED_BALANCED_ALT_B_PRIMARY = 55,
    RELATION_SPATIAL_CONTROL_GAPPED_BALANCED_ALT_B_SHAM = 56
} relation_spatial_control_id;

typedef struct relation_spatial_preparation {
    uint32_t bank_a_work;
    uint32_t bank_b_work;
    relation_spatial_relation_id relation;
    relation_spatial_order_id source_order;
    uint32_t cyclic_origin;
} relation_spatial_preparation;

typedef struct relation_spatial_carrier_state {
    uint8_t lane_a[FAMILY10H_RELATION_SPATIAL_LANE_BYTES];
    uint8_t lane_b[FAMILY10H_RELATION_SPATIAL_LANE_BYTES];
    uint8_t sham_a[FAMILY10H_RELATION_SPATIAL_LANE_BYTES];
    uint8_t sham_b[FAMILY10H_RELATION_SPATIAL_LANE_BYTES];
} relation_spatial_carrier_state;

uint32_t relation_spatial_map_index(relation_spatial_relation_id relation, uint32_t logical_a_index);
uint32_t relation_spatial_origin_index(uint32_t cyclic_origin, uint32_t step);
void relation_spatial_prefault(relation_spatial_carrier_state *state);
int relation_spatial_prepare(relation_spatial_preparation prep, relation_spatial_carrier_state *state);
int relation_spatial_runtime_self_test(void);
int relation_spatial_runtime_live_authority_present(void);

#endif
